### ISSUE TITLE
Differentiate required and optional arguments from the spec

### ISSUE THREAD

**Issue by rofinn** [denvrdata/denvrpy#4]
Right now, we don't differentiate between required and optional arguments being sent to the API; this might be added to make error handling and testing more explicit.

**Comment by rofinn** [comment]
Looks like in python3 we could just handle this in the generated function definition by using the `*` argument after. This makes all subsequent arguments keywords, but we can choose to not provide a default value of `None` making it required. This is nice cause it doesn't introduce extra error types and just makes it part of the API.

```
>>> def f(*, b, a, d="foo", c="bar"):
...     print("{} {} {} {}".format(a, b, c, d))
...
>>> >>> f(1, 2)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    f(1, 2)
TypeError: f() takes 0 positional arguments but 2 were given
>>> f(a=1, b=2)
1 2 bar foo
>>> f(b=1, a=2)
2 1 bar foo
>>> f(b=2, a=1)
1 2 bar foo
>>> f(c=4, a=1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    f(c=4, a=1)
TypeError: f() missing 1 required keyword-only argument: 'b'
```
